name: Deploy Flutter Web

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16'
        
    - name: Flutter Channel
      run: flutter channel master
        
    - name: Flutter upgrade
      run: flutter upgrade
 
    - name: Install Dependencies
      run: flutter pub get

    - name: Check and Remove Existing Build Directory
      run: |
        if [ -d "build/web" ]; then
          echo "Removing existing build directory."
          rm -rf build/web
        fi

    - name: Build Web
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web